# -*- coding: utf-8 -*-

SITES = [
    {
        "name": "教务处",
        "category": "重要",
        "base": "https://jwc.ytu.edu.cn/",
        "list_url": "https://jwc.ytu.edu.cn/index/tzgg.htm",
        "page_pattern": "https://jwc.ytu.edu.cn/index/tzgg/{page}.htm",
        "max_pages": 50,
        "container": "div.main_conRCb",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "学生工作处（武装部）",
        "category": "其他",
        "base": "https://stu.ytu.edu.cn/",
        "list_url": "https://stu.ytu.edu.cn/index/tzgg.htm",
        "page_pattern": "https://stu.ytu.edu.cn/index/tzgg/{page}.htm",
        "max_pages": 50,
        "container": "div#right_nei",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "科技处-科技动态",
        "category": "科研竞赛",
        "base": "https://kjc.ytu.edu.cn/",
        "list_url": "https://kjc.ytu.edu.cn/kjdt.htm",
        "page_pattern": "https://kjc.ytu.edu.cn/kjdt/{page}.htm",
        "max_pages": 50,
        "container": "body",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "学科竞赛网",
        "category": "科研竞赛",
        "base": "https://xkjs.ytu.edu.cn/",
        "list_url": "https://xkjs.ytu.edu.cn/list.jsp?a9t=10&a9p=1&a9c=10&urltype=tree.TreeTempUrl&wbtreeid=1046",
        "page_pattern": "https://xkjs.ytu.edu.cn/list.jsp?a9t=10&a9p={page}&a9c=10&urltype=tree.TreeTempUrl&wbtreeid=1046",
        "max_pages": 20,
        "container": "body",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "研究生处",
        "category": "研究生",
        "base": "https://yjs.ytu.edu.cn/",
        "list_url": "https://yjs.ytu.edu.cn/xwgz/tzgg.htm",
        "page_pattern": "https://yjs.ytu.edu.cn/xwgz/tzgg/{page}.htm",
        "max_pages": 20,
        "container": "body",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "校医院-通知公告",
        "category": "其他",
        "base": "https://hospital.ytu.edu.cn/",
        "list_url": "https://hospital.ytu.edu.cn/tzgg.htm",
        "page_pattern": "https://hospital.ytu.edu.cn/tzgg/{page}.htm",
        "max_pages": 5,
        "container": "ul.dj_lb1",
        "link_filter": None,
        "allow_external": True,
    },
    # ===== 新增：信息公开网 =====
    {
        "name": "信息公开-学生管理",
        "category": "重要",
        "base": "https://gk.ytu.edu.cn/",
        "list_url": "https://gk.ytu.edu.cn/xxgkml/xsgl.htm",
        "page_pattern": "https://gk.ytu.edu.cn/xxgkml/xsgl/{page}.htm",
        "max_pages": 2,
        "page_reverse": True,          # 【新】递减翻页
        "container": "ul.list",
        "link_filter": "info/",
        "allow_external": False,
    },
    {
        "name": "信息公开-目录",
        "category": "其他",
        "base": "https://gk.ytu.edu.cn/",
        "list_url": "https://gk.ytu.edu.cn/xxgkml.htm",
        "page_pattern": "https://gk.ytu.edu.cn/xxgkml/{page}.htm",
        "max_pages": 64,
        "page_reverse": True,          # 【新】递减翻页
        "container": "ul.list",
        "link_filter": "info/",
        "allow_external": False,
    },
    # ===== 就业信息网 =====
    {
        "name": "就业信息网",
        "category": "其他",
        "type": "json",
        "api_url": "https://school.gxjy.sdei.edu.cn/ytu/school/Notice/indexList/2",
        "params": {"pageNum": 1, "pageSize": 10},
        "title_field": "noticeTitle",
        "date_field": "showtime",
        "id_field": "noticeId",
        "url_template": "https://school.gxjy.sdei.edu.cn/ytu/school/Notice/detail/{id}",
        "fileurl_field": "fileurl",
        "referer": "https://school.gxjy.sdei.edu.cn/ytu/front/NoticeList?deptId=2",
    },
]
